# Generated by Django 3.2.16 on 2023-04-14 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_count', models.IntegerField(default=0)),
                ('chat_gpt_plus', models.BooleanField(default=True)),
                ('chat_gpt_plus_premium', models.BooleanField(default=False)),
                ('custom_chatbot_count', models.IntegerField(default=0)),
                ('add_files_or_link', models.IntegerField(default=0)),
                ('files_count', models.IntegerField(default=0)),
                ('pages_count', models.IntegerField(default=0)),
                ('mb_count', models.IntegerField(default=0)),
                ('share_link_with_anyone', models.BooleanField(default=False)),
                ('embed_in_your_website', models.BooleanField(default=False)),
                ('remove_rafiq_branding', models.BooleanField(default=False)),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('email_support', models.BooleanField(default=False)),
                ('chat_bot_access', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('FREE', 'FREE'), ('BASIC', 'BASIC'), ('PRO', 'PRO'), ('BUSINESS', 'BUSINESS')], max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('features', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionfeatures')),
            ],
        ),
    ]
