# Generated by Django 3.2.16 on 2023-04-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriptionfeatures_add_files_or_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplans',
            name='subscription_tenure',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'MONTHLY'), ('ANUAL', 'ANUAL')], max_length=500, null=True),
        ),
    ]
