# Generated by Django 3.2.16 on 2023-04-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplans_subscription_tenure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplans',
            name='subscription_tenure',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'MONTHLY'), ('ANUAL', 'ANUAL')], default='MONTHLY', max_length=500, null=True),
        ),
    ]
