# Generated by Django 3.2.16 on 2023-04-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_cards_paymentshistory_stripecustomer_stripesetupintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionfeatures',
            name='webpages_count',
            field=models.IntegerField(default=100),
        ),
    ]
