# Generated by Django 3.2.16 on 2023-04-14 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Chatbots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('data_language', models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('NOT-ENGLISH', 'NOT-ENGLISH')], default='ENGLISH', max_length=15)),
                ('data_source', models.CharField(choices=[('FILES', 'FILES'), ('WEBSITE', 'WEBSITE'), ('FILES & WEBSITE', 'FILES & WEBSITE')], default='FILES', max_length=15)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='chatbot_files', to='chatbots.Documents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
