# Generated by Django 3.2.16 on 2023-04-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0003_conversation_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbots',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='messages',
            name='context_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='messages',
            name='stand_alone_query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
