# Generated by Django 3.2.16 on 2023-04-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0004_auto_20230415_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbots',
            name='vector_store',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
