# Generated by Django 3.2.16 on 2023-04-20 23:03

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbots', '0006_auto_20230419_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='GptMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(blank=True, null=True)),
                ('cost', models.FloatField(default=0.0)),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatbots',
            name='embedding',
            field=models.CharField(blank=True, choices=[('OPENAI', 'OPENAI'), ('COHERE', 'COHERE')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='source',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GptConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ManyToManyField(blank=True, related_name='chat_gpt', to='chatbots.Messages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
