# Generated by Django 3.2.16 on 2023-04-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0010_auto_20230424_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='file_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
