# Generated by Django 3.2.16 on 2023-04-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0011_documents_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
