# Generated by Django 3.2.16 on 2023-04-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0012_documents_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='type',
            field=models.CharField(choices=[('FILES', 'FILES'), ('WEBSITE', 'WEBSITE')], default='FILES', max_length=15),
        ),
        migrations.AddField(
            model_name='documents',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
