# Generated by Django 3.2.16 on 2023-04-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0013_auto_20230425_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='type',
            field=models.CharField(choices=[('DOCUMENT', 'DOCUMENT'), ('WEBSITE', 'WEBSITE')], default='FILES', max_length=15),
        ),
    ]
