# Generated by Django 3.2.16 on 2023-04-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0014_alter_documents_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
