# Generated by Django 3.2.16 on 2023-05-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0016_savedchatbots_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='source',
        ),
    ]
