# Generated by Django 3.2.16 on 2023-04-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('OPENAI', 'OPENAI'), ('COHERE', 'COHERE')], default='OPENAI', max_length=15)),
            ],
        ),
    ]
