# Generated by Django 3.2.16 on 2023-04-20 23:03

from django.db import migrations, models
from dotenv import load_dotenv

import os
load_dotenv()
COHERE_KEY = os.getenv('COHERE_KEY')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faq_featurevideo_testomonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('question', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='embedding',
            name='cohere_api_key',
            field=models.CharField(default=COHERE_KEY, max_length=1000),
        ),
        migrations.AddField(
            model_name='embedding',
            name='open_api_key',
            field=models.CharField(default=OPENAI_API_KEY, max_length=1000),
        ),
        migrations.AddField(
            model_name='embedding',
            name='prompt_message',
            field=models.TextField(default='You are a personal growth assistant. Your job is to help the users with their questions. You are given the following extracted parts of a long document and a user input. Provide an answer with atleast 300 words for the following user input.'),
        ),
    ]
