# Generated by Django 3.2.16 on 2023-04-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221106_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('USER', 'USER'), ('ADMIN', 'ADMIN')], max_length=10, null=True),
        ),
    ]
