# Generated by Django 3.2.16 on 2023-04-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230416_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_start',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_renew_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_stripe_subscription_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
